name: Build

on:
  push:
    branches:
      - main  # Build on every push to main
  pull_request:
    branches:
      - main  # Build on PRs to main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build AOT Release
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishAot=true -p:PublishSingleFile=false -o ./publish
      
    - name: Create distribution package
      run: |
        # Create release directory structure
        New-Item -ItemType Directory -Force -Path ./release
        
        # Copy executable
        Copy-Item ./publish/tsw6-realtime-weather.exe ./release/
        
        # Copy config template
        Copy-Item ./config.yaml ./release/config.yaml
        
        # Copy README
        Copy-Item ./README.md ./release/
        
        # Create a usage instructions file
        @"
        TSW6 Realtime Weather - Quick Start
        ====================================
        
        1. Make sure Train Sim World 6 is installed
        2. Edit config.yaml and add your OpenWeather API key:
           - Get a free API key from: https://openweathermap.org/api
           - Update the 'openweather' field under 'api_keys'
        
        3. Launch TSW6 with the -HTTPAPI flag:
           - Right-click TSW6 in Steam
           - Properties → General → Launch Options
           - Add: -HTTPAPI
        
        4. Run tsw6-realtime-weather.exe
        
        5. Start playing TSW6 and drive around!
        
        Configuration:
        - weather.update_threshold_km: Distance to travel before weather updates (default: 10 km)
        - update.location_check_interval_seconds: How often to check location (default: 10 seconds)
        - retry.max_retries: HTTP retry attempts (default: 5)
        - logging.level: Debug, Information, Warning, or Error (default: Information)
        
        Logs are saved to TSW6RealtimeWeather.log in the same directory.
        
        For more information, see README.md
        "@ | Out-File -FilePath ./release/QUICKSTART.txt -Encoding UTF8
        
    - name: Create ZIP archive
      run: |
        $version = if ($env:GITHUB_REF -match 'refs/tags/(.*)') { 
          $matches[1] 
        } elseif ($env:GITHUB_SHA) {
          "dev-$($env:GITHUB_SHA.Substring(0,7))"
        } else { 
          "dev" 
        }
        Compress-Archive -Path ./release/* -DestinationPath "./tsw6-realtime-weather-$version-windows-x64.zip"
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "ZIP_FILE=tsw6-realtime-weather-$version-windows-x64.zip" >> $env:GITHUB_ENV
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: tsw6-realtime-weather-${{ env.VERSION }}-windows-x64
        path: ./tsw6-realtime-weather-*.zip
        retention-days: 90
